version: "3"
services:
  reverse-proxy:
    image: traefik
    command: --api.insecure=true --providers.docker --providers.docker.exposedByDefault=false
    restart: "no"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  rgbmicroservice:
    build: ../rgbmicroservice
    restart: "no"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rgbmicroservice.rule=PathPrefix(`/HexService/FromHexToRgb`)"
      - "traefik.http.routers.rgbmicroservice.middlewares=rgbmicroservice-stripprefix"
      - "traefik.http.services.rgbmicroservice.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.rgbmicroservice-stripprefix.stripprefix.prefixes=/HexService/FromHexToRgb"
